name: Build AndUEDumper x86_64
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Setup CMake
        run: sudo apt-get install -y cmake ninja-build

      - name: Build
        run: |
          cd AndUEDumper
          echo "1" | bash build.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UEDumper-x86_64
          path: "**/x86_64/*"
