name: Build AndUEDumper x86_64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Build
        run: |
          cd AndUEDumper
          chmod +x build.sh
          bash build.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: UEDumper-x86_64
          path: "**/x86_64/*"
